name: luci-app-passwall CI
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

      
jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      URL: https://downloads.openwrt.org/snapshots/targets/mediatek/filogic/openwrt-sdk-mediatek-filogic_gcc-12.2.0_musl.Linux-x86_64.tar.xz
    
    steps:
    - name: Checkout - clone repository
      uses: actions/checkout@v1
    
    - name: Download and untar sdk
      run: |
        wget $URL
        tar xvJf openwrt-sdk-mediatek-filogic_gcc-12.2.0_musl.Linux-x86_64.tar.xz
    
    - name: SSH链接管理
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        
#     - name: Configure sdk
#       run: cp ./openwrt-sdk-mediatek-filogic_gcc-12.2.0_musl.Linux-x86_64/.config
      
    - name: Install dependencies
      run: |
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion git-core gcc-multilib libelf-dev autoconf automake libtool
        sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

        
    - name: Clone package
      run: |
        cd openwrt-sdk-mediatek-filogic_gcc-12.2.0_musl.Linux-x86_64/package/
        git clone https://github.com/Leslie-Wong/luci-app-passwall.git
    - name: Build ipk
      run: |
        cd openwrt-sdk-mediatek-filogic_gcc-12.2.0_musl.Linux-x86_64
        make package/luci-app-passwall/compile V=99
    - name: Upload - push to artifact file
      uses: actions/upload-artifact@v1
      with:
        name: luci-app-passwall
        path: openwrt-sdk-mediatek-filogic_gcc-12.2.0_musl.Linux-x86_64/bin/packages/*/base
